# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maps.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 881)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.satellite_btn = QtWidgets.QPushButton(self.centralwidget)
        self.satellite_btn.setGeometry(QtCore.QRect(920, 250, 121, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.satellite_btn.setFont(font)
        self.satellite_btn.setObjectName("satellite_btn")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(20, 60, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clear_btn.setFont(font)
        self.clear_btn.setObjectName("clear_btn")
        self.scheme_btn = QtWidgets.QPushButton(self.centralwidget)
        self.scheme_btn.setGeometry(QtCore.QRect(920, 120, 121, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.scheme_btn.setFont(font)
        self.scheme_btn.setObjectName("scheme_btn")
        self.hybrid_btn = QtWidgets.QPushButton(self.centralwidget)
        self.hybrid_btn.setGeometry(QtCore.QRect(920, 370, 121, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hybrid_btn.setFont(font)
        self.hybrid_btn.setObjectName("hybrid_btn")
        self.seaarch_line = QtWidgets.QLineEdit(self.centralwidget)
        self.seaarch_line.setGeometry(QtCore.QRect(20, 10, 631, 51))
        self.seaarch_line.setObjectName("seaarch_line")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(660, 10, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.search_btn.setFont(font)
        self.search_btn.setObjectName("search_btn")
        self.map = QtWidgets.QLabel(self.centralwidget)
        self.map.setGeometry(QtCore.QRect(20, 120, 871, 721))
        self.map.setObjectName("map")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.satellite_btn.setText(_translate("MainWindow", "Спутник"))
        self.clear_btn.setText(_translate("MainWindow", "Сбросить запрос"))
        self.scheme_btn.setText(_translate("MainWindow", "Схема"))
        self.hybrid_btn.setText(_translate("MainWindow", "Гибрид"))
        self.search_btn.setText(_translate("MainWindow", "Искать"))
        self.map.setText(_translate("MainWindow", "Картинка карты"))
